name: hyperpartisan
dependencies:
  - gensim=3.4.0
  - keras=2.2.4
  - nltk=3.4.1
  - python=3.6
  - pytorch=0.4.1
  - scikit-learn=0.20
  - spacy=2.0.16
  - tensorflow=1.12.0
  - pip:
    - allennlp

